### ISSUE TITLE
JavaScript property color mismatch

### ISSUE THREAD

**Issue by vinnlee** [liviuschera/noctis#4]
I noticed there is a difference in color of property in javascript, like the image below

![image](https://user-images.githubusercontent.com/20036316/47541418-59d41280-d903-11e8-8bab-155af71a72a4.png)

**Comment by liviuschera** [comment]
Hey mate! That was a good catch. 

I had a cursory look over the issue and apparently VS Code's JavaScript language grammar fails to pick up DOM properties in a consistent manner.

I'll investigate further and see how can I fix it.

**Comment by liviuschera** [comment]
I have released a fix for this issue in v3.19.2

I would appreciate if you woud try it and let me know how it works for you.

**Comment by vinnlee** [comment]
Hmm.... 🤔 I just updated the theme and have a look at my js source code.
The issue is partial fixed, but it seems inconsistent, some properties still doesn't have same color,
Don't know this is by the theme or vscode itself 🤔, I have tested with other theme but doesn't see this issue. 🤨

**Comment by liviuschera** [comment]
Thanks for your feedback, mate. 

I had a proper look into the matter and the conclusion is that VS Codes's JavaScript language grammar is broken when it comes to properly highlight DOM properties.

Because I wanted DOM objects like `document`, `screen`, `window` and DOM properties like `height`, `backgroundPosition`, `backgroundImage`, `name`, `location`, etc. to stand out I decided to highlight them with the Desert Sand color. I'm using this color exclusively to for DOM highlighting. 

I would have liked that all the DOM properties in the screenshot you provided to be highlighted in Desert Sand color. Unfortunately, as I said, right now VS Code JS grammar picks up only partially DOM object properties. That's why `backgroundSize` and `backgroundPosition` were not properly highlighted and that’s why you noticed the highlighting inconsistencies.

Having said that I still want that DOM object related syntax to be highlighted with Desert Sand color, but to get rid of the blatant mismatches I narrowed down the scope selectors that are being picked up by VS Code’s highlighter.

As an example, the highlighting of `location.pathname` , `document.title` and `name` is intentional.

![github noctis issue 4](https://user-images.githubusercontent.com/12068956/47632158-82247100-db90-11e8-89c8-58884cdbd4d7.png)

I hope this sheds some light on this topic if not please feel free to ask or add any thoughts you might have.

Cheers!
